---
title: " "
author:
  - 蔡佳泓
date: \today
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: no
  includes:    
    in_header: header.tex
classoption: "hyperref,"
---


1.您对于台湾大选的观点及分析？

2020年大选结果最终由台湾领导人蔡英文和民进党民意代表取得多数压倒性胜利。您是否预判到会有这样的结果？如果是，您为何事先会有这样的评估和判断？另一方面，如果本次选举结果是出乎预料，有哪些方面让您觉得最出乎意料，与事先的评估相左？

\medskip
回覆：個人從上次的投票結果以及11月的民調結果，並且觀察選舉前的民調，判斷蔡英文將獲得57\%的選票，韓國瑜41\%，後來證明高估韓國瑜2\%。個人原本預期投票率應該只有五成多，但是事後證明過於低估。
\medskip

2.您如何看待本次选举结果的影响因素和台湾岛内情势？

2020年选举的结果是台湾领导人蔡英文获得817万票，这是台湾选举历史上最高的一次得票数，而政党的投票结果是民进党获得33％的支持率和13个比例代表，而国民党也获得33％和13个比例代表。可是与上届一样民进党能获得过半的议会席次而完全执政的结果，但台湾媒体（尤其是联合报和中国时报等）认为，这是台湾人反中情绪和由此引发的危机结果。首先是去年在香港发生的返送中游行的影响，其次，习近平主席在2018年1月的演讲中提到，与台湾统一计划相关的一国两制台湾方案，再其次是国民党内部的劣势（在比例代表上的提名问题、以及国民党内部问题与候选人韩国瑜的亲中立场等）。您如何看待这次选举结果？以及是否有对于本次选举的其他观点？

\medskip
回覆：個人基本上贊成外在因素有利於民進黨操作反中的情緒，但是國民黨本身不團結也是主因。雖然韓國瑜親中、沒有治理的成績，但是還是獲得五百多萬票，比朱立倫還多，顯示還是很多人討厭民進黨，只是國民黨從上到下實在沒有規劃，不然其實韓國瑜可以拉抬國民黨更多。
\medskip


3.您如何看待台湾的代沟问题(世代、省籍和职业等)？您如何看待台湾的年轻一代？

从台湾大选的结果来看，我认为台湾年轻人对民族认同的认知变化速度较快，是造成国民党分歧和失败的主要原因之一。换句话说，台湾青年比中国青年更具有自我意识。我听过对台湾年轻世代的统独意识的说明里天然独与理性统的分别，这次选举是否仍然天然独比理性统占了更多的优势固定的评价？

从长远来看，台湾大多数民众认为两岸统一的期望会越来越小。您怎么看待此一问题？

\medskip
回覆：這次選舉的確刺激台灣民眾的國家認同，過去部分民眾覺得台灣終將會被中國統一的心態，可能漸漸轉變為台灣應該努力維持現狀而不是消極地接受中國越來越強大的事實。目前大概接近三成的台灣民眾贊成獨立，隨著這次武漢肺炎繼續威脅台灣人的生命安全，贊成的比例應該還會增加。
\medskip


4中国对此次大选以后的未来政策及做法是什么？在和平统一和武力统一的可能比率是多少？

我认为中国的对台政策是有两面性的。中国领导人习近平国家主席身旁应有鹰派和鸽派，鹰派试图通过外交压力和军事威胁来限缩台湾的国际空间，让台湾当局（或民众）希望两岸和平、做两岸协商的政策变化。鸽派试图惠台政策和统一战线方针也希望让台湾会接受一国两制和平统一方案。在这种环境下，这次台湾大选以后您认为未来习近平的对台政策是否将有所改变，而一国两制的台湾方案是否也有可能更名或是有所改变？我认为中国选择武统的可能性极小，也许继续坚持和平统一方式。这样的话会不会选择联邦制或国家联合制度方式做两岸统一的可能性。

\medskip
回覆：我看不出來習近平會採用一國兩制以外的方案，或許他會思考先度過中美貿易戰再選擇更強硬還是和緩的手段。
\medskip


5. 2020年台湾大选后在中国发生了新冠肺炎，我认为新冠肺炎对中国，亚洲和世界的生命、卫生和健康的影响，以及对中国本身内部政治、经济、社会和国际关系，也造成严重的影响和后果，迄今为止后续的影响也持续扩大。您如何看待这次疫情对中国的政治和国际影响？在一部分少数国家也有相关的排华活动，是否会影响未来中国对其他国家的外交政策。台湾当局也实行大陆游客不准入台政策，这是否会影响两岸关系？


\medskip
回覆：這次疫情的確會讓台灣民眾對於中國產生不好的印象，對於中國觀光客帶來的負面作用可能更會警惕，雖然觀光業仍然仰賴於中國觀光客。兩岸關係已經很壞，經過武漢台商的包機事件以及縮減直航班次等事件，短期內更難改善。
\medskip


